version: '2'

networks:
  intnet:
    driver: bridge

services:
  db_re:
    container_name: rethinkdb
    image: rethinkdb:latest
    networks:
      - intnet
    ports:
      - 8081:8080
      - 29015:29015
      - 28015:28015
    volumes:
      - ${PWD}/rethinkdb:/data
    command: rethinkdb --bind all -d /data 
  db:
    container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: changeme
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme
    networks:
      - intnet
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
      - ${PWD}/mariadb/mysql_sock:/var/run/mysqld
  app:
    container_name: app
    build: ./app
    networks:
      - intnet
    ports:
      - 8090:80
  phpfpm:
    container_name: phpfpm
    image: bitnami/php-fpm:latest
    networks:
      - intnet
    volumes:
      - ${PWD}/api:/app
      - ${PWD}/config/php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ${PWD}/config/php.ini:/opt/bitnami/php/etc/conf.d/app.ini
      - ${PWD}/mariadb/mysql_sock:/var/run/mysqld
  composer:
    container_name: composer
    restart: 'no'
    image: composer
    command: install
    volumes:
      - ${PWD}/api:/app
  nginx:
    container_name: web
    image: bitnami/nginx:latest
    links:
      - phpfpm
      - app
    depends_on:
      - phpfpm
      - app
    networks:
      - intnet
    ports:
      - 80:8080
    volumes:
      - ./config/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./config/api.conf:/opt/bitnami/nginx/conf/server_blocks/api.conf
      - ${PWD}/app:/app
